export { default as Header } from "./layout/Header";
export { default as Footer } from "./layout/Footer";
export { default as HeroSection } from "../components/home/HeroSection";
export { default as Why_grafixy } from "../components/home/Why_grafixy";
export { default as WorkSession } from "../components/home/WorkSession";
export { default as Collaboration } from "../components/home/Collaboration";
export { default as Free_trail } from "../components/home/Free_trail";
export { default as HomeFAQ } from "../components/home/HomeFAQ";
export { default as Testimonial  } from "../components/home/Testimonial";
